title: Import your own sounds
hero_image: images/banner.png
description: Import your own sounds
version: 4
listed: false
copyedit: false
last_tested: "2021-11-30"
steps:
  - 
    title: Import your own sounds
